source("Rscripts/QuitarNa/1 ImputeValues.R")
source("Rscripts/QuitarNa/2 SeparareImputar.R")
source("Rscripts/Glm/SepararFactores.R")
source("Rscripts/Glm/SeleccionColumnas.R")
source("Rscripts/Glm/BaseGenerico.R")
source("Rscripts/Glm/GlmGenerico.R")
source("Rscripts/Glm/ParaPredecirGenerico.R")
source("Rscripts/Glm/PrediccionGlmGenerico.R")
source("Rscripts/Lm/PorcAprobado.R")
source("Rscripts/Lm/LmGenerico.R")
source("Rscripts/Lm/PrediccionLmGenerico.R")